"""
Ion Zarija, José Villalba
22/01/2024
ASIXc1A M03 UF1 A5 pr5
"""
CAS = ("abanto", "abrazafarolas", "adufe", "alcornoque", "alfeñique", "andurriasmo", "arrastracueros", "artabán", "atarre", "baboso", "barrabás", "barriobajero", "bebecharcos", "bellaco", "belloto", "berzotas", "besugo", "bobalicón", "bocabuzón", "bocachancla", "bocallanta", "boquimuelle", "borrico", "botarate", "brasas", "cabestro", "cabezaalberca", "cabezabuque", "cachibache", "cafre", "cagalindes", "cagarruta", "calambuco", "calamidad", "caldúo", "calientahielos", "calzamonas", "cansalmas", "cantamañanas", "capullo", "caracaballo", "caracartón", "caraculo", "caraflema", "carajaula", "carajote", "carapapa", "carapijo", "cazurro", "cebollino", "cenizo", "cenutrio", "ceporro", "cernícalo", "charrán", "chiquilicuatre", "chirimbaina", "chupacables", "chupasangre", "chupóptero", "cierrabares", "cipote", "comebolsas", "comechapas", "comeflores", "comestacas", "cretino", "cuerpoescombro", "culopollo", "descerebrado", "desgarracalzas", "dondiego", "donnadie", "echacantos", "ejarramantas", "energúmeno", "esbaratabailes", "escolimoso", "escornacabras", "estulto", "fanfosquero", "fantoche", "fariseo", "filimincias", "foligoso", "fulastre", "ganapán", "ganapio", "gandúl", "gañán", "gaznápiro", "gilipuertas", "giraesquinas", "gorrino", "gorrumino", "guitarro", "gurriato", "habahelá", "huelegateras", "huevón", "lamecharcos", "lameculos", "lameplatos", "lechuguino", "lerdo", "letrín", "lloramigas", "longanizas", "lumbreras", "maganto", "majadero", "malasangre", "malasombra", "malparido", "mameluco", "mamporrero", "manegueta", "mangarrán", "mangurrián", "mastuerzo", "matacandiles", "meapilas", "melón", "mendrugo", "mentecato", "mequetrefe", "merluzo", "metemuertos", "metijaco", "mindundi", "morlaco", "morroestufa", "muerdesartenes", "orate", "ovejo", "pagafantas", "palurdo", "pamplinas", "panarra", "panoli", "papafrita", "papanatas", "papirote", "paquete", "pardillo", "parguela", "pasmarote", "pasmauegras", "pataliebre", "patán", "pavitonto", "pazguato", "pecholata", "pedorro", "peinabombillas", "peinaovejas", "pelagallos", "pelagambas", "pelagatos", "pelatigres", "pelazarzas", "pelele", "pelma", "percebe", "perrocostra", "perroflauta", "peterete", "petimetre", "picapleitos", "pichabrava", "pillavispas", "piltrafa", "pinchauvas", "pintamonas", "piojoso", "pitañoso", "pitofloro", "plomo", "pocasluces", "pollopera", "quitahipos", "rastrapajo", "rebañasandías", "revientabaules", "ríeleches", "robaperas", "sabandija", "sacamuelas", "sanguijuela", "sinentraero", "sinsustancia", "sonajas", "sonso", "soplagaitas", "soplaguindas", "sosco", "tagarote", "tarado", "tarugo", "tiralevitas", "tocapelotas", "tocho", "tolai", "tontaco", "tontucio", "tordo", "tragaldabas", "tuercebotas", "tunante", "zamacuco", "zambombo", "zampabollos", "zamugo", "zángano", "zarrapastroso", "zascandil", "zopenco", "zoquete", "zote", "zullenco", "zurcefrenillos")
CAT = ("abanto", "abraçafanals", "adufa", "alzina", "alfenic", "andurriasmu", "arrossegacuirs", "artabán", "atarre", "babau", "barrabàs", "barriobaix", "begueixarregots", "bellac", "bellot", "berzotas", "besuc", "bobalicon", "bocabuzó", "bocaxancla", "bocallanta", "bocamuell", "borrí", "botarate", "brases", "cabestre", "cabeçaalberca", "cabezabuque", "cachibac", "cafre", "cagalindes", "cagarruta", "calambuc", "calamitat", "caldú", "calentagels", "calçamones", "cansalmes", "cantamañanes", "capullo", "caracavall", "cartró", "caraculo", "caraflama", "caragaiola", "carajaula", "carajote", "carapapa", "carapicó", "cazur", "cebollí", "ceniza", "cenutri", "ceporro", "cernícalo", "xarrán", "xiquilicuatre", "xirimbaina", "xupacables", "xupasang", "xupópter", "cerraferres", "cipot", "menjabosses", "menjaplatós", "menjaflors", "menjatacos", "cretí", "cosgro", "culopol", "descervellat", "desgarracames", "dondiego", "donnadie", "eixacantós", "ejarremantas", "energúmen", "esbaratabailes", "escolimos", "esquenaconills", "estult", "fanfosquer", "fantotxe", "fariseu", "filimíncies", "foligós", "fulastre", "ganapá", "ganapio", "gandúl", "ganyan", "gaznàp", "gilipertes", "giraesquenes", "gorrí", "gorrumí", "guitarro", "gurriat", "habahelá", "olfegateres", "ovó", "lamexarcots", "lameculs", "lameplats", "llepolino", "lerd", "letrí", "ploramiques", "llonganisses", "llumbreres", "magant", "majacó", "malasang", "malasombra", "malparit", "mameluc", "mamporrer", "maneguet", "mangarran", "mangurrian", "mastuerç", "matacanóts", "meapiles", "meló", "mendrú", "mentecat", "mengerefe", "merluç", "metemorts", "metixac", "mindundi", "morlaco", "morroestufa", "mordiscapans", "demente", "ovell", "pagafantes", "palurd", "pamplines", "panar", "panoli", "papafrita", "papanates", "papirot", "paquet", "pardilló", "parguela", "pasmagorda", "pasmases", "patalieb", "patan", "pavitonto", "pacauet", "pecholat", "petor", "penaombolles", "peinaovelles", "pelagall", "pelagambes", "pelagats", "pelatigre", "pelarras", "pelele", "pelma", "percebe", "perrocostra", "perroflauta", "peteret", "petimet", "picapleitos", "pitxabrava", "pillavisques", "piltrafa", "pincavaxes", "pintamones", "piojós", "pitaños", "pitoflor", "plom", "poca llum", "pollópera", "llarga-pilós", "rastrapall", "trebanegues", "rebanhagulles", "revientaxiscles", "rielixos", "rovapaires", "sabandija", "sacamuelas", "sangonja", "sinentraero", "sensesubstància", "sonalles", "sons", "bufagaietes", "bufaguindes", "sosc", "tagarot", "tarad", "tarugo", "tira-nadons", "tocapelotes", "troç", "tolai", "tonto", "tontússio", "tord", "tragaollons", "torçbotes", "tunant", "zamacuc", "zambombo", "zampabolles", "zamug", "zàngan", "zarrapastroso", "zascandil", "zopenc", "xoc", "zote", "zullenc", "zurcefregalls")

pos = 0
try:
   user = str(input("Introduce insulto"))
   while pos < len(CAS) and CAS[pos] != user and CAT[pos] != user:
      pos += 1

   if pos < len(CAS):
      print(CAS[pos], CAT[pos])
   else:
      print("Insulto no encontrado en las listas")

except ValueError:
   print("No has introducido una palabra")


